#! /bin/sh
# $Id$

# Fail on error
autoreconf -v -i || exit 1

echo
echo -------------------------------------------------------------------------
echo Binaries linked against libsuzerain.la run into linker problems because
echo current versions of libtool do not preserve OpenMP flags.  Workaround per
echo http://lists.gnu.org/archive/html/bug-libtool/2011-03/msg00015.html.
echo -------------------------------------------------------------------------
echo

patch -p0 -N -r - --verbose <<\EOF
--- build-aux/ltmain.sh
+++ build-aux/ltmain.sh
@@ -5643,7 +5643,7 @@
 	continue
 	;;
 
+      -mt|-mthreads|-kthread|-Kthread|-pthread|-pthreads|--thread-safe|-threads|-fopenmp|-openmp|-mp|-xopenmp|-omp|-qsmp=omp)
-      -mt|-mthreads|-kthread|-Kthread|-pthread|-pthreads|--thread-safe|-threads)
 	func_append compiler_flags " $arg"
 	func_append compile_command " $arg"
 	func_append finalize_command " $arg"
@@ -6147,7 +6147,7 @@
 	lib=
 	found=no
 	case $deplib in
+	-mt|-mthreads|-kthread|-Kthread|-pthread|-pthreads|--thread-safe|-threads|-fopenmp|-openmp|-mp|-xopenmp|-omp|-qsmp=omp)
-	-mt|-mthreads|-kthread|-Kthread|-pthread|-pthreads|--thread-safe|-threads)
 	  if test "$linkmode,$pass" = "prog,link"; then
 	    compile_deplibs="$deplib $compile_deplibs"
 	    finalize_deplibs="$deplib $finalize_deplibs"
EOF
# From 'man 1 patch': "... patch exits with status 1 if some
# hunks failed, or with  2  if there  was real trouble."
if test $? -gt 1; then
    exit 1
fi
