#! /bin/bash
# $Id$

# Fail on error
autoreconf -v -i || exit 1

echo
echo -------------------------------------------------------------------------
echo -------------------------- LIBTOOL PATCHES ------------------------------
echo -------------------------------------------------------------------------
echo 1\) Binaries linked against libsuzerain.la run
echo into linker problems because current versions of
echo libtool do not preserve OpenMP flags.  Workaround per
echo http://lists.gnu.org/archive/html/bug-libtool/2011-03/msg00015.html.
echo
echo 2\) Enable -R propagation from convenience libraries. See
echo http://lists.gnu.org/archive/html/automake/2011-03/msg00049.html
echo -------------------------------------------------------------------------
echo

patch -p0 -N --verbose <<\EOF
--- build-aux/ltmain.sh
+++ build-aux/ltmain.sh
@@ -5643,7 +5643,7 @@
 	continue
 	;;
 
+      -mt|-mthreads|-kthread|-Kthread|-pthread|-pthreads|--thread-safe|-threads|-fopenmp|-openmp|-mp|-xopenmp|-omp|-qsmp=omp)
-      -mt|-mthreads|-kthread|-Kthread|-pthread|-pthreads|--thread-safe|-threads)
 	func_append compiler_flags " $arg"
 	func_append compile_command " $arg"
 	func_append finalize_command " $arg"
@@ -6147,7 +6147,7 @@
 	lib=
 	found=no
 	case $deplib in
+	-mt|-mthreads|-kthread|-Kthread|-pthread|-pthreads|--thread-safe|-threads|-fopenmp|-openmp|-mp|-xopenmp|-omp|-qsmp=omp)
-	-mt|-mthreads|-kthread|-Kthread|-pthread|-pthreads|--thread-safe|-threads)
 	  if test "$linkmode,$pass" = "prog,link"; then
 	    compile_deplibs="$deplib $compile_deplibs"
 	    finalize_deplibs="$deplib $finalize_deplibs"
--- build-aux/ltmain.sh
+++ build-aux/ltmain.sh
@@ -7127,7 +7127,9 @@
 	    # practice:
 	    case $deplib in
 	    -L*) new_libs="$deplib $new_libs" ;;
+	    ##Enable -R propagation from convenience libraries.  See
+	    ##http://lists.gnu.org/archive/html/automake/2011-03/msg00049.html
+	    ##-R*) ;;
-	    -R*) ;;
 	    *)
 	      # And here is the reason: when a library appears more
 	      # than once as an explicit dependence of a library, or
EOF
# From 'man 1 patch': "... patch exits with status 1 if some
# hunks failed, or with  2  if there  was real trouble."
if test $? -gt 1; then
    exit 1
fi

if test -d "largo"; then
    echo
    echo ------------------------------------------
    echo Bootstrapping Largo in subdirectory largo/
    echo ------------------------------------------
    echo
    (cd largo && ./bootstrap) || exit 1
fi
