/* This file was generated by the "svnrev" utility
 * (http://www.compuphase.com/svnrev.htm).
 * You should not modify it manually, as it may be re-generated.
 * 
 * $Revision: 4666M$
 * $Date: 2012-02-27$
 */

#ifndef SVN_REV_H
#define SVN_REV_H

#define SVN_REV		4666
#define SVN_REVSTR	"4666"
#define SVN_REVDATE	"2012-02-27"
#define SVN_REVSTAMP	20120227L
#define SVN_REVMODIFIED	0

#endif /* SVN_REV_H */
